# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af8835fbebaa3c86ab3ffff4cc1d925b0560cc16af53c67ea467d4b644a99db3f928549f8e2b69209cc675447bae1b4e0a50cec25b7c9eda342d982fb859e186

test:
  secret_key_base: 3866f31173f65f0a1870b6fb843ddabd1b0a146bff462fc838730d6cfc853ee3af7da90a35923425f316a48553c24737a2b871c0c80c9d7d6a5355bb594445b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
